[package]
name = "osinfo"
version = "1.0.0"
edition = "2021"

[dependencies]
# external dependencies
serde_json = { workspace = true }
# workspace crate dependencies
dsc-lib-osinfo = { workspace = true }
