[package]
name = "dsc-resource-echo"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "dscecho"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rust-i18n = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
