[package]
name = "dscecho"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
rust-i18n = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
