# For testing outside of the repository, set the schema in the yaml server directive to:
#    https://raw.githubusercontent.com/PowerShell/DSC/main/v3/resource/manifest.json
#
# Hover on the keys to see the documentation. Try changing values and adding new settings.
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/v3/config/document.json
# Try adding the variables, metadata, and parameters properties,
# then use IntelliSense to define a few entries.

resources:
  - type: example/resource
    name: My Example
    properties:
      foo: bar
  # Define a new resource instance
