[package]
name = "runcommandonset"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
rust-i18n = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
