[package]
name = "security_context_lib"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")'.dependencies]
is_elevated = { workspace = true }

[target.'cfg(not(target_os = "windows"))'.dependencies]
nix = { workspace = true, features = ["user"] }
