[package]
name = "dsc-resource-run_command_on_set"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "runcommandonset"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rust-i18n = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
