[package]
name = "dsc-resource-process"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "process"
path = "src/main.rs"

[dependencies]
sysinfo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
